//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBReader2.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TBReader2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Author 的本地化字符串。
        /// </summary>
        internal static string en_about_author_label {
            get {
                return ResourceManager.GetString("en_about_author_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;b&gt;ABOUT&lt;/b&gt; 的本地化字符串。
        /// </summary>
        internal static string en_about_button {
            get {
                return ResourceManager.GetString("en_about_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 E-mail 的本地化字符串。
        /// </summary>
        internal static string en_about_email_label {
            get {
                return ResourceManager.GetString("en_about_email_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Read TXT in title bar!&lt;br/&gt;Thank you for your support! 的本地化字符串。
        /// </summary>
        internal static string en_about_intro {
            get {
                return ResourceManager.GetString("en_about_intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Intro 的本地化字符串。
        /// </summary>
        internal static string en_about_intro_label {
            get {
                return ResourceManager.GetString("en_about_intro_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version 的本地化字符串。
        /// </summary>
        internal static string en_about_version_label {
            get {
                return ResourceManager.GetString("en_about_version_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 30 (sec) 的本地化字符串。
        /// </summary>
        internal static string en_apt_end_label {
            get {
                return ResourceManager.GetString("en_apt_end_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Page Turn 的本地化字符串。
        /// </summary>
        internal static string en_apt_label {
            get {
                return ResourceManager.GetString("en_apt_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0 (sec)&lt;br/&gt;Manual 的本地化字符串。
        /// </summary>
        internal static string en_apt_start_label {
            get {
                return ResourceManager.GetString("en_apt_start_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (sec) 的本地化字符串。
        /// </summary>
        internal static string en_apt_tooltip {
            get {
                return ResourceManager.GetString("en_apt_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;b&gt;HOTKEYS&lt;/b&gt; 的本地化字符串。
        /// </summary>
        internal static string en_hotkey_button {
            get {
                return ResourceManager.GetString("en_hotkey_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next Line 的本地化字符串。
        /// </summary>
        internal static string en_hotkey1 {
            get {
                return ResourceManager.GetString("en_hotkey1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Previous Line 的本地化字符串。
        /// </summary>
        internal static string en_hotkey2 {
            get {
                return ResourceManager.GetString("en_hotkey2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bookmark current line 的本地化字符串。
        /// </summary>
        internal static string en_hotkey3 {
            get {
                return ResourceManager.GetString("en_hotkey3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Jump through bookmarks 的本地化字符串。
        /// </summary>
        internal static string en_hotkey4 {
            get {
                return ResourceManager.GetString("en_hotkey4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Jump to previous location&lt;br/&gt;(ONLY under bookmark view) 的本地化字符串。
        /// </summary>
        internal static string en_hotkey5 {
            get {
                return ResourceManager.GetString("en_hotkey5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toggle default title/current line 的本地化字符串。
        /// </summary>
        internal static string en_hotkey6 {
            get {
                return ResourceManager.GetString("en_hotkey6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toggle TBReader2 hide/show 的本地化字符串。
        /// </summary>
        internal static string en_hotkey7 {
            get {
                return ResourceManager.GetString("en_hotkey7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quit 的本地化字符串。
        /// </summary>
        internal static string en_hotkey8 {
            get {
                return ResourceManager.GetString("en_hotkey8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        internal static string en_ok_button {
            get {
                return ResourceManager.GetString("en_ok_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text File|*.txt 的本地化字符串。
        /// </summary>
        internal static string en_openFileDialog_filter {
            get {
                return ResourceManager.GetString("en_openFileDialog_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choose a TXT file 的本地化字符串。
        /// </summary>
        internal static string en_openFileDialog_title {
            get {
                return ResourceManager.GetString("en_openFileDialog_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drag a TXT file here 的本地化字符串。
        /// </summary>
        internal static string en_pictureBox_string_1 {
            get {
                return ResourceManager.GetString("en_pictureBox_string_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OR... Double click here 的本地化字符串。
        /// </summary>
        internal static string en_pictureBox_string_2 {
            get {
                return ResourceManager.GetString("en_pictureBox_string_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 作者 的本地化字符串。
        /// </summary>
        internal static string zh_about_author_label {
            get {
                return ResourceManager.GetString("zh_about_author_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;b&gt;关于&lt;/b&gt; 的本地化字符串。
        /// </summary>
        internal static string zh_about_button {
            get {
                return ResourceManager.GetString("zh_about_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮箱 的本地化字符串。
        /// </summary>
        internal static string zh_about_email_label {
            get {
                return ResourceManager.GetString("zh_about_email_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标题栏中看小说！&lt;br/&gt;谢谢支持！ 的本地化字符串。
        /// </summary>
        internal static string zh_about_intro {
            get {
                return ResourceManager.GetString("zh_about_intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 简介 的本地化字符串。
        /// </summary>
        internal static string zh_about_intro_label {
            get {
                return ResourceManager.GetString("zh_about_intro_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本 的本地化字符串。
        /// </summary>
        internal static string zh_about_version_label {
            get {
                return ResourceManager.GetString("zh_about_version_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 30 秒 的本地化字符串。
        /// </summary>
        internal static string zh_apt_end_label {
            get {
                return ResourceManager.GetString("zh_apt_end_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动翻页 的本地化字符串。
        /// </summary>
        internal static string zh_apt_label {
            get {
                return ResourceManager.GetString("zh_apt_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0 秒&lt;br/&gt;手动翻页 的本地化字符串。
        /// </summary>
        internal static string zh_apt_start_label {
            get {
                return ResourceManager.GetString("zh_apt_start_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 秒 的本地化字符串。
        /// </summary>
        internal static string zh_apt_tooltip {
            get {
                return ResourceManager.GetString("zh_apt_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;b&gt;热键说明&lt;/b&gt; 的本地化字符串。
        /// </summary>
        internal static string zh_hotkey_button {
            get {
                return ResourceManager.GetString("zh_hotkey_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下一行 的本地化字符串。
        /// </summary>
        internal static string zh_hotkey1 {
            get {
                return ResourceManager.GetString("zh_hotkey1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上一行 的本地化字符串。
        /// </summary>
        internal static string zh_hotkey2 {
            get {
                return ResourceManager.GetString("zh_hotkey2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加当前行为书签 的本地化字符串。
        /// </summary>
        internal static string zh_hotkey3 {
            get {
                return ResourceManager.GetString("zh_hotkey3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 循环跳转所有书签 的本地化字符串。
        /// </summary>
        internal static string zh_hotkey4 {
            get {
                return ResourceManager.GetString("zh_hotkey4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回到之前的位置&lt;br/&gt;（只在查看书签时有效） 的本地化字符串。
        /// </summary>
        internal static string zh_hotkey5 {
            get {
                return ResourceManager.GetString("zh_hotkey5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换当前内容/真正标题 的本地化字符串。
        /// </summary>
        internal static string zh_hotkey6 {
            get {
                return ResourceManager.GetString("zh_hotkey6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示/隐藏TBReader2 的本地化字符串。
        /// </summary>
        internal static string zh_hotkey7 {
            get {
                return ResourceManager.GetString("zh_hotkey7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        internal static string zh_hotkey8 {
            get {
                return ResourceManager.GetString("zh_hotkey8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        internal static string zh_ok_button {
            get {
                return ResourceManager.GetString("zh_ok_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本文件|*.txt 的本地化字符串。
        /// </summary>
        internal static string zh_openFileDialog_filter {
            get {
                return ResourceManager.GetString("zh_openFileDialog_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择TXT文件 的本地化字符串。
        /// </summary>
        internal static string zh_openFileDialog_title {
            get {
                return ResourceManager.GetString("zh_openFileDialog_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拖拽TXT文件到框内 的本地化字符串。
        /// </summary>
        internal static string zh_pictureBox_string_1 {
            get {
                return ResourceManager.GetString("zh_pictureBox_string_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 或者双击框内 的本地化字符串。
        /// </summary>
        internal static string zh_pictureBox_string_2 {
            get {
                return ResourceManager.GetString("zh_pictureBox_string_2", resourceCulture);
            }
        }
    }
}
