//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBReader2.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TBReader2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap clock {
            get {
                object obj = ResourceManager.GetObject("clock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Author 的本地化字符串。
        /// </summary>
        internal static string en_about_author_label {
            get {
                return ResourceManager.GetString("en_about_author_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;b&gt;ABOUT&lt;/b&gt; 的本地化字符串。
        /// </summary>
        internal static string en_about_button {
            get {
                return ResourceManager.GetString("en_about_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 E-mail 的本地化字符串。
        /// </summary>
        internal static string en_about_email_label {
            get {
                return ResourceManager.GetString("en_about_email_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Read TXT in title bar!&lt;br/&gt;Thank you for your support! 的本地化字符串。
        /// </summary>
        internal static string en_about_intro {
            get {
                return ResourceManager.GetString("en_about_intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Intro 的本地化字符串。
        /// </summary>
        internal static string en_about_intro_label {
            get {
                return ResourceManager.GetString("en_about_intro_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version 的本地化字符串。
        /// </summary>
        internal static string en_about_version_label {
            get {
                return ResourceManager.GetString("en_about_version_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 30 (sec) 的本地化字符串。
        /// </summary>
        internal static string en_apt_end_label {
            get {
                return ResourceManager.GetString("en_apt_end_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Page Turn 的本地化字符串。
        /// </summary>
        internal static string en_apt_label {
            get {
                return ResourceManager.GetString("en_apt_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0 (sec)&lt;br/&gt;Manual 的本地化字符串。
        /// </summary>
        internal static string en_apt_start_label {
            get {
                return ResourceManager.GetString("en_apt_start_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (sec) 的本地化字符串。
        /// </summary>
        internal static string en_apt_tooltip {
            get {
                return ResourceManager.GetString("en_apt_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update failed!&lt;br/&gt;Please try again later! 的本地化字符串。
        /// </summary>
        internal static string en_autoUpdater_msg_failed {
            get {
                return ResourceManager.GetString("en_autoUpdater_msg_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed 的本地化字符串。
        /// </summary>
        internal static string en_autoUpdater_msg_failed_title {
            get {
                return ResourceManager.GetString("en_autoUpdater_msg_failed_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Success!&lt;br/&gt;Application restarts in 5 seconds! 的本地化字符串。
        /// </summary>
        internal static string en_autoUpdater_msg_success {
            get {
                return ResourceManager.GetString("en_autoUpdater_msg_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Success 的本地化字符串。
        /// </summary>
        internal static string en_autoUpdater_msg_success_title {
            get {
                return ResourceManager.GetString("en_autoUpdater_msg_success_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update terminated!&lt;br/&gt;Cannot complete update! 的本地化字符串。
        /// </summary>
        internal static string en_autoUpdater_msg_terminated {
            get {
                return ResourceManager.GetString("en_autoUpdater_msg_terminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Terminated 的本地化字符串。
        /// </summary>
        internal static string en_autoUpdater_msg_terminated_title {
            get {
                return ResourceManager.GetString("en_autoUpdater_msg_terminated_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Latest version already! 的本地化字符串。
        /// </summary>
        internal static string en_autoUpdater_result_latest {
            get {
                return ResourceManager.GetString("en_autoUpdater_result_latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No update info found! 的本地化字符串。
        /// </summary>
        internal static string en_autoUpdater_result_none {
            get {
                return ResourceManager.GetString("en_autoUpdater_result_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string en_button_cancel {
            get {
                return ResourceManager.GetString("en_button_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        internal static string en_button_ok {
            get {
                return ResourceManager.GetString("en_button_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;b&gt;HOTKEYS&lt;/b&gt; 的本地化字符串。
        /// </summary>
        internal static string en_hotkey_button {
            get {
                return ResourceManager.GetString("en_hotkey_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next Line 的本地化字符串。
        /// </summary>
        internal static string en_hotkey1 {
            get {
                return ResourceManager.GetString("en_hotkey1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Previous Line 的本地化字符串。
        /// </summary>
        internal static string en_hotkey2 {
            get {
                return ResourceManager.GetString("en_hotkey2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bookmark current line 的本地化字符串。
        /// </summary>
        internal static string en_hotkey3 {
            get {
                return ResourceManager.GetString("en_hotkey3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Jump through bookmarks 的本地化字符串。
        /// </summary>
        internal static string en_hotkey4 {
            get {
                return ResourceManager.GetString("en_hotkey4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Jump to previous location&lt;br/&gt;(ONLY under bookmark view) 的本地化字符串。
        /// </summary>
        internal static string en_hotkey5 {
            get {
                return ResourceManager.GetString("en_hotkey5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toggle default title/current line 的本地化字符串。
        /// </summary>
        internal static string en_hotkey6 {
            get {
                return ResourceManager.GetString("en_hotkey6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toggle TBReader2 hide/show 的本地化字符串。
        /// </summary>
        internal static string en_hotkey7 {
            get {
                return ResourceManager.GetString("en_hotkey7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quit 的本地化字符串。
        /// </summary>
        internal static string en_hotkey8 {
            get {
                return ResourceManager.GetString("en_hotkey8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 One file at a time! 的本地化字符串。
        /// </summary>
        internal static string en_only_single_file {
            get {
                return ResourceManager.GetString("en_only_single_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TXT file only! 的本地化字符串。
        /// </summary>
        internal static string en_only_txt_file {
            get {
                return ResourceManager.GetString("en_only_txt_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text File|*.txt 的本地化字符串。
        /// </summary>
        internal static string en_openFileDialog_filter {
            get {
                return ResourceManager.GetString("en_openFileDialog_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choose a TXT file 的本地化字符串。
        /// </summary>
        internal static string en_openFileDialog_title {
            get {
                return ResourceManager.GetString("en_openFileDialog_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drag a TXT file here 的本地化字符串。
        /// </summary>
        internal static string en_pictureBox_string_1 {
            get {
                return ResourceManager.GetString("en_pictureBox_string_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OR... Double click here 的本地化字符串。
        /// </summary>
        internal static string en_pictureBox_string_2 {
            get {
                return ResourceManager.GetString("en_pictureBox_string_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Completed:  的本地化字符串。
        /// </summary>
        internal static string en_update_completed {
            get {
                return ResourceManager.GetString("en_update_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cur Version 的本地化字符串。
        /// </summary>
        internal static string en_update_cur {
            get {
                return ResourceManager.GetString("en_update_cur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update Description 的本地化字符串。
        /// </summary>
        internal static string en_update_description {
            get {
                return ResourceManager.GetString("en_update_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download Update 的本地化字符串。
        /// </summary>
        internal static string en_update_download {
            get {
                return ResourceManager.GetString("en_update_download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Downloaded:  的本地化字符串。
        /// </summary>
        internal static string en_update_downloaded {
            get {
                return ResourceManager.GetString("en_update_downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Downloading Update ... 的本地化字符串。
        /// </summary>
        internal static string en_update_downloading {
            get {
                return ResourceManager.GetString("en_update_downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update found! 的本地化字符串。
        /// </summary>
        internal static string en_update_found {
            get {
                return ResourceManager.GetString("en_update_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update found 的本地化字符串。
        /// </summary>
        internal static string en_update_found_title {
            get {
                return ResourceManager.GetString("en_update_found_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Version 的本地化字符串。
        /// </summary>
        internal static string en_update_new {
            get {
                return ResourceManager.GetString("en_update_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Verifying Update ... 的本地化字符串。
        /// </summary>
        internal static string en_update_verifying {
            get {
                return ResourceManager.GetString("en_update_verifying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 作者 的本地化字符串。
        /// </summary>
        internal static string zh_about_author_label {
            get {
                return ResourceManager.GetString("zh_about_author_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;b&gt;关于&lt;/b&gt; 的本地化字符串。
        /// </summary>
        internal static string zh_about_button {
            get {
                return ResourceManager.GetString("zh_about_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮箱 的本地化字符串。
        /// </summary>
        internal static string zh_about_email_label {
            get {
                return ResourceManager.GetString("zh_about_email_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标题栏中看小说！&lt;br/&gt;谢谢支持！ 的本地化字符串。
        /// </summary>
        internal static string zh_about_intro {
            get {
                return ResourceManager.GetString("zh_about_intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 简介 的本地化字符串。
        /// </summary>
        internal static string zh_about_intro_label {
            get {
                return ResourceManager.GetString("zh_about_intro_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本 的本地化字符串。
        /// </summary>
        internal static string zh_about_version_label {
            get {
                return ResourceManager.GetString("zh_about_version_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 30 秒 的本地化字符串。
        /// </summary>
        internal static string zh_apt_end_label {
            get {
                return ResourceManager.GetString("zh_apt_end_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动翻页 的本地化字符串。
        /// </summary>
        internal static string zh_apt_label {
            get {
                return ResourceManager.GetString("zh_apt_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0 秒&lt;br/&gt;手动翻页 的本地化字符串。
        /// </summary>
        internal static string zh_apt_start_label {
            get {
                return ResourceManager.GetString("zh_apt_start_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 秒 的本地化字符串。
        /// </summary>
        internal static string zh_apt_tooltip {
            get {
                return ResourceManager.GetString("zh_apt_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新出错！&lt;br/&gt;请稍后再试一次！ 的本地化字符串。
        /// </summary>
        internal static string zh_autoUpdater_msg_failed {
            get {
                return ResourceManager.GetString("zh_autoUpdater_msg_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新出错 的本地化字符串。
        /// </summary>
        internal static string zh_autoUpdater_msg_failed_title {
            get {
                return ResourceManager.GetString("zh_autoUpdater_msg_failed_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新成功！&lt;br/&gt;程序5秒后即将自动重启！ 的本地化字符串。
        /// </summary>
        internal static string zh_autoUpdater_msg_success {
            get {
                return ResourceManager.GetString("zh_autoUpdater_msg_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新成功 的本地化字符串。
        /// </summary>
        internal static string zh_autoUpdater_msg_success_title {
            get {
                return ResourceManager.GetString("zh_autoUpdater_msg_success_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新过程被中断！&lt;br/&gt;无法完成更新！ 的本地化字符串。
        /// </summary>
        internal static string zh_autoUpdater_msg_terminated {
            get {
                return ResourceManager.GetString("zh_autoUpdater_msg_terminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新中断 的本地化字符串。
        /// </summary>
        internal static string zh_autoUpdater_msg_terminated_title {
            get {
                return ResourceManager.GetString("zh_autoUpdater_msg_terminated_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已经是最新版本！ 的本地化字符串。
        /// </summary>
        internal static string zh_autoUpdater_result_latest {
            get {
                return ResourceManager.GetString("zh_autoUpdater_result_latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有找到更新信息！ 的本地化字符串。
        /// </summary>
        internal static string zh_autoUpdater_result_none {
            get {
                return ResourceManager.GetString("zh_autoUpdater_result_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string zh_button_cancel {
            get {
                return ResourceManager.GetString("zh_button_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        internal static string zh_button_ok {
            get {
                return ResourceManager.GetString("zh_button_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;b&gt;热键说明&lt;/b&gt; 的本地化字符串。
        /// </summary>
        internal static string zh_hotkey_button {
            get {
                return ResourceManager.GetString("zh_hotkey_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下一行 的本地化字符串。
        /// </summary>
        internal static string zh_hotkey1 {
            get {
                return ResourceManager.GetString("zh_hotkey1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上一行 的本地化字符串。
        /// </summary>
        internal static string zh_hotkey2 {
            get {
                return ResourceManager.GetString("zh_hotkey2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加当前行为书签 的本地化字符串。
        /// </summary>
        internal static string zh_hotkey3 {
            get {
                return ResourceManager.GetString("zh_hotkey3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 循环跳转所有书签 的本地化字符串。
        /// </summary>
        internal static string zh_hotkey4 {
            get {
                return ResourceManager.GetString("zh_hotkey4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回到之前的位置&lt;br/&gt;（只在查看书签时有效） 的本地化字符串。
        /// </summary>
        internal static string zh_hotkey5 {
            get {
                return ResourceManager.GetString("zh_hotkey5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换当前内容/真正标题 的本地化字符串。
        /// </summary>
        internal static string zh_hotkey6 {
            get {
                return ResourceManager.GetString("zh_hotkey6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示/隐藏TBReader2 的本地化字符串。
        /// </summary>
        internal static string zh_hotkey7 {
            get {
                return ResourceManager.GetString("zh_hotkey7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        internal static string zh_hotkey8 {
            get {
                return ResourceManager.GetString("zh_hotkey8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只能拖入一个文件！ 的本地化字符串。
        /// </summary>
        internal static string zh_only_single_file {
            get {
                return ResourceManager.GetString("zh_only_single_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只能拖入TXT文件！ 的本地化字符串。
        /// </summary>
        internal static string zh_only_txt_file {
            get {
                return ResourceManager.GetString("zh_only_txt_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本文件|*.txt 的本地化字符串。
        /// </summary>
        internal static string zh_openFileDialog_filter {
            get {
                return ResourceManager.GetString("zh_openFileDialog_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择TXT文件 的本地化字符串。
        /// </summary>
        internal static string zh_openFileDialog_title {
            get {
                return ResourceManager.GetString("zh_openFileDialog_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拖拽TXT文件到框内 的本地化字符串。
        /// </summary>
        internal static string zh_pictureBox_string_1 {
            get {
                return ResourceManager.GetString("zh_pictureBox_string_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 或者双击框内 的本地化字符串。
        /// </summary>
        internal static string zh_pictureBox_string_2 {
            get {
                return ResourceManager.GetString("zh_pictureBox_string_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已完成： 的本地化字符串。
        /// </summary>
        internal static string zh_update_completed {
            get {
                return ResourceManager.GetString("zh_update_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前版本 的本地化字符串。
        /// </summary>
        internal static string zh_update_cur {
            get {
                return ResourceManager.GetString("zh_update_cur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新内容 的本地化字符串。
        /// </summary>
        internal static string zh_update_description {
            get {
                return ResourceManager.GetString("zh_update_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载更新 的本地化字符串。
        /// </summary>
        internal static string zh_update_download {
            get {
                return ResourceManager.GetString("zh_update_download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已下载： 的本地化字符串。
        /// </summary>
        internal static string zh_update_downloaded {
            get {
                return ResourceManager.GetString("zh_update_downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在下载更新…… 的本地化字符串。
        /// </summary>
        internal static string zh_update_downloading {
            get {
                return ResourceManager.GetString("zh_update_downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有新版本发布！ 的本地化字符串。
        /// </summary>
        internal static string zh_update_found {
            get {
                return ResourceManager.GetString("zh_update_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测到更新 的本地化字符串。
        /// </summary>
        internal static string zh_update_found_title {
            get {
                return ResourceManager.GetString("zh_update_found_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新版本 的本地化字符串。
        /// </summary>
        internal static string zh_update_new {
            get {
                return ResourceManager.GetString("zh_update_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证更新…… 的本地化字符串。
        /// </summary>
        internal static string zh_update_verifying {
            get {
                return ResourceManager.GetString("zh_update_verifying", resourceCulture);
            }
        }
    }
}
